version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, pr_build]
    default: pr_build
  dry_run:
    type: boolean
    default: true
    description: "Run in dry run mode?"
  maven_profile_id:
    type: string
    default: "gravitee-dry-run"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.4

jobs:
  chromatic:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore `node_modules` cache
          keys:
            - node-modules-cache-{{ checksum "package-lock.json" }}
            - node-modules-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save `node_modules` cache
          key: node-modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Building Storybook
          command: npm run build
      - run:
          name: Running Chromatic
          command: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded -d=storybook-static

workflows:
  version: 2.1
  pull_requests:
    when:
      equal: [ pr_build, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/pr-build:
          context: cicd-orchestrator
  visual-testing:
    when:
      equal: [ pr_build, << pipeline.parameters.gio_action >> ]
    jobs:
      - chromatic:
          context: cicd-orchestrator
  release:
    # see https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - not: << pipeline.parameters.dry_run >>
    jobs:
      # return to simple definition :
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>
  release_dry_run:
    # see https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - << pipeline.parameters.dry_run >>
    jobs:
      # return to simple definition :
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>
